import { NextApiRequest, NextApiResponse } from "next";
import { prisma } from "@/lib/prisma";
import UserSession from "@/services/UserSession";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
    try {
        const token = req.cookies.userSession;
        if (!token) {
            return res.status(401).json({ success: false, message: "Unauthorized" });
        }

        const sessionResult = await UserSession(token);
        if (!sessionResult.success) {
            return res.status(401).json({ success: false, message: sessionResult.message });
        }

        const userId = sessionResult.data.userId;

        if (req.method === "POST") {
            const { title = "Test Notification", message = "This is a test notification generated by the system.", type = "INFO", link } = req.body;

            const notification = await prisma.notification.create({
                data: {
                    userId,
                    title,
                    message,
                    type,
                    link
                }
            });

            return res.status(200).json({ success: true, data: notification });
        }

        return res.status(405).json({ success: false, message: "Method not allowed" });
    } catch (error: any) {
        console.error("Test Create Notification API Error:", error);
        return res.status(500).json({ success: false, message: "Internal server error" });
    }
}
